"""One ordered variant form for FASTQ setup and existing-BAM setup."""
from html import escape
from .variant_model_assets import CLAIR3_PROFILES, CLAIRSTO_PLATFORMS


def path_field(key, label, *, kind='folder', hint='', detect=True, placeholder='Autodetect or choose a path'):
    button = (f'<button type="button" data-variant-detect="{key}" aria-label="Autodetect {escape(label)}">Autodetect</button>' if detect else '')
    return f'''<div class="variant-path"><label for="{key}">{label}</label>
<div class="variant-path-row"><input id="{key}" spellcheck="false" autocomplete="off" placeholder="{placeholder}">
<div class="variant-path-actions">{button}<button type="button" data-browse="{key}" data-kind="{kind}">Browse</button></div></div>
<p id="{key}-status" class="variant-path-status hint" aria-live="polite"></p>{f'<p class="hint">{hint}</p>' if hint else ''}</div>'''


def variant_form(*, existing_bam=False):
    clair3_options = ''.join(f'<option value="{escape(key)}">{escape(value["label"])}</option>' for key, value in CLAIR3_PROFILES.items())
    clairsto_options = ''.join(f'<option value="{escape(key)}">{escape(value)}</option>' for key, value in CLAIRSTO_PLATFORMS.items())
    specimen = 'specimen' if existing_bam else 'variant'
    callers = 'callers' if existing_bam else 'variant-callers'
    clair3 = 'clair3-fields' if existing_bam else 'variant-clair3-field'
    clairsto = 'clairsto-fields' if existing_bam else 'variant-clairsto-field'
    ffpe = 'ffperase-section' if existing_bam else 'variant-ffperase-fields'
    ffpe_paths = 'ffperase-resource-fields' if existing_bam else 'variant-ffperase-resource-fields'
    varlo = 'varlociraptor-fields' if existing_bam else 'variant-varlociraptor-fields'
    annovar = 'annovar-fields' if existing_bam else 'variant-annovar-fields'
    note = 'caller-note' if existing_bam else 'variant-preservation-note'
    threads = '<div class="field variant-short"><label for="threads">CPU threads</label><input id="threads" type="number" min="1" step="1" value="4"></div>' if existing_bam else ''
    return f'''<div class="variant-form">
<nav class="variant-nav" aria-label="Variant settings"><button type="button" data-variant-section="variant-specimen-section">1 · Specimen &amp; callers</button><button type="button" data-variant-section="variant-tools-section">2 · Tools &amp; models</button><button type="button" data-variant-section="variant-filter-section">3 · Filtering</button><button type="button" data-variant-section="variant-annotation-section">4 · Annotation</button></nav>
<section class="variant-section" id="variant-specimen-section" aria-labelledby="variant-specimen-title">
<div class="variant-section-heading"><span class="variant-step">1</span><div><h3 id="variant-specimen-title">Specimen and callers</h3><p class="hint">Choose the preservation and the analyses to run.</p></div></div>
<div class="variant-specimen" role="group" aria-label="Sample preservation"><button type="button" class="platform" id="{specimen}-fresh" aria-pressed="false"><strong>Fresh</strong><span>Fresh or frozen material</span></button><button type="button" class="platform" id="{specimen}-ffpe" aria-pressed="false"><strong>FFPE</strong><span>Formalin-fixed tissue</span></button></div>
<p id="{note}" class="hint" role="status">Choose Fresh or FFPE from your specimen records.</p>
<div id="variant-caller-settings" hidden><h4>Variant callers</h4><div id="{callers}" class="variant-caller-list" role="group" aria-label="Variant callers"></div>
<details class="variant-explainer"><summary>How caller results are used</summary><p class="hint">Mutect2 and ClairS-TO produce tumor-only candidates. FreeBayes, bcftools and Clair3 use germline-style calling. Each sample is analyzed independently; Normal and Cancer assignments do not create matched pairs or establish somatic origin.</p></details></div>
</section>
<section class="variant-section" hidden id="variant-tools-section" aria-labelledby="variant-tools-title">
<div class="variant-section-heading"><span class="variant-step">2</span><div><h3 id="variant-tools-title">Caller tools and models</h3><p class="hint">Start with Autodetect. Open paths only to review or change them.</p></div></div>
<!-- VARIANT_RESOURCE_PANEL -->
<p id="variant-tool-note" class="hint"></p>{threads}
<div id="variant-tool-prefix-fields"><details class="variant-path-details"><summary>Caller environment <span class="variant-path-summary" data-path-summary="variant_tool_prefix"></span></summary>
{path_field('variant_tool_prefix', 'Variant tool environment', hint='Leave blank to use tools already available to OncoTracer.')}</details></div>
<div id="{clair3}" class="variant-tool-block" hidden><h4>Clair3 model</h4><label for="variant-clair3-source">Model preparation</label><select id="variant-clair3-source"><option value="auto">Automatic · download and verify when the run starts</option><option value="local">Use an existing model folder</option></select><div id="variant-clair3-auto-fields"><label for="variant_ont_profile">Flow cell and basecalling model used for these reads</label><select id="variant_ont_profile">{clair3_options}</select><p class="hint">Check this selection against your sequencing records. Fresh/FFPE does not determine the flow cell or basecaller. The matching model is about 75 MB, downloaded once and reused.</p></div><div id="variant-clair3-local-fields" hidden>{path_field('variant_clair3_model','Clair3 model folder',placeholder='Choose a model compatible with your reads')}</div></div>
<div id="{clairsto}" class="variant-tool-block" hidden><h4>ClairS-TO model</h4><label for="variant-clairsto-preset">Sequencing and basecaller profile</label><select id="variant-clairsto-preset">{clairsto_options}<option value="custom">Other installed preset (advanced)</option></select><p class="hint">Uses the selected model from the ClairS-TO installation or container. Check the flow cell, basecaller version and sampling rate against your sequencing records.</p><div id="variant-clairsto-custom" hidden><label for="variant_clairsto_platform">Custom installed preset name</label><input id="variant_clairsto_platform" placeholder="Exact preset from your installed ClairS-TO version"><button type="button" data-variant-detect="variant_clairsto_platform">Model guidance</button></div><div id="variant-clairsto-sif-fields"><details class="variant-path-details"><summary>Use an existing ClairS-TO container (optional) <span class="variant-path-summary" data-path-summary="variant_clairsto_sif"></span></summary>{path_field('variant_clairsto_sif','ClairS-TO SIF',kind='asset',hint='An alternative to the installed executable. Requires local Apptainer or Singularity.')}</details></div></div>
<details class="variant-path-details"><summary>Target regions (optional)</summary>{path_field('variant_targets_bed','Variant target BED',kind='asset',detect=False,placeholder='Empty = whole genome',hint='Choose the BED for your assay and reference build. Target regions are not guessed automatically.')}</details>
</section>
<section class="variant-section" hidden id="variant-filter-section" aria-labelledby="variant-filter-title">
<div class="variant-section-heading"><span class="variant-step">3</span><div><h3 id="variant-filter-title">Variant filtering</h3><p class="hint" id="variant-filter-note">Caller quality filters are applied automatically.</p></div></div>
<div id="{ffpe}" class="variant-tool-block" hidden><div class="variant-block-heading"><h4>FFPERASE artifact assessment</h4><button type="button" data-variant-detect="ffperase">Autodetect FFPERASE</button></div><label for="variant_ffperase">FFPE assessment</label><select id="variant_ffperase"><option value="required">Run FFPERASE (required)</option><option value="off">Skip FFPERASE</option></select>
<div id="{ffpe_paths}"><label class="check"><input type="checkbox" id="variant_download_resources" checked>Prepare missing FFPERASE source and models when the run starts</label><p class="hint">Existing paths are reused. Public resources are verified and cached in this project's results folder. The FFPERASE runtime still needs to be installed, or use Docker.</p><div id="variant-ffperase-license"><label class="check"><input type="checkbox" id="variant_accept_ffperase_license">I have reviewed and accept the FFPERASE license for downloading and using its resources.</label><p class="hint"><a href="https://github.com/papaemmelab/nf-ffperase/blob/b0dd56cbd0a939896a966b9ce30c4d719b158170/LICENSE" target="_blank" rel="noopener noreferrer">Review the FFPERASE license</a> before enabling automatic preparation. The license excludes clinical reporting and requires MSK permission to publish research results. Existing local resources can be supplied below.</p></div><p class="variant-required-summary" data-path-summary="variant_ffperase_root,variant_ffperase_models" data-required-path="true"></p><details class="variant-path-details"><summary>FFPERASE source and models</summary>{path_field('variant_ffperase_root','FFPERASE source folder')}{path_field('variant_ffperase_models','FFPERASE models folder')}</details>
<div id="variant-ffperase-runtime-fields"><details class="variant-path-details"><summary>FFPERASE runtime <span class="variant-path-summary" data-path-summary="variant_ffperase_prefix,variant_ffperase_sif"></span></summary><label for="variant-ffperase-runtime">Run FFPERASE with</label><select id="variant-ffperase-runtime"><option value="native">Native Python environment</option><option value="sif">Existing SIF container</option></select><div id="variant-ffperase-prefix-fields">{path_field('variant_ffperase_prefix','FFPERASE Python environment')}</div><div id="variant-ffperase-sif-fields">{path_field('variant_ffperase_sif','FFPERASE SIF',kind='asset')}</div></details></div></div></div>
<div class="variant-tool-block"><label for="variant_varlociraptor">Additional confidence filtering with Varlociraptor</label><select id="variant_varlociraptor"><option value="off">Use the caller's standard quality filters</option><option value="required">Also assess variant evidence with Varlociraptor</option></select><div id="{varlo}" hidden><p class="notice">The standard model assesses whether a variant is present. No YAML file or sample key is needed. Default local false discovery rate: 5%.</p><button type="button" data-variant-detect="variant_tool_prefix">Check Varlociraptor tools</button><details class="variant-path-details"><summary>Advanced evidence settings</summary><div class="field variant-short"><label for="variant_varlociraptor_fdr">Local false discovery rate</label><input id="variant_varlociraptor_fdr" type="number" min="0.000001" max="0.999999" step="any" value="0.05"></div><label for="variant-scenario-mode">Evidence model</label><select id="variant-scenario-mode"><option value="standard">Standard variant presence (recommended)</option><option value="custom">Custom scenario YAML</option></select><div id="variant-custom-scenario" hidden>{path_field('variant_varlociraptor_scenario','Custom Varlociraptor scenario YAML',kind='file',detect=False,placeholder='Choose your scenario YAML',hint='For custom statistical models only. Use the event and sample keys defined inside that YAML.')}<div class="grid"><div><label for="variant_varlociraptor_events">Event keys defined in the YAML</label><input id="variant_varlociraptor_events" value="PRESENT"></div><div><label for="variant_varlociraptor_sample">Sample key defined in the YAML</label><input id="variant_varlociraptor_sample" value="sample"></div></div><p class="hint">This is the model's internal sample key, not a patient or barcode identifier.</p></div></details></div></div>
</section>
<section class="variant-section" hidden id="variant-annotation-section" aria-labelledby="variant-annotation-title">
<div class="variant-section-heading"><span class="variant-step">4</span><div><h3 id="variant-annotation-title">Annotation</h3><p class="hint">Use your local ANNOVAR installation and matching databases.</p></div></div>
<label for="variant_annovar">ANNOVAR annotation</label><select id="variant_annovar"><option value="auto">Use ANNOVAR when available</option><option value="off">Skip ANNOVAR annotation</option></select>
<div id="{annovar}"><div class="variant-block-heading"><p class="hint" data-path-summary="variant_annovar_dir,variant_annovar_db"></p><button type="button" data-variant-detect="annotation">Autodetect ANNOVAR</button></div><details class="variant-path-details"><summary>Installation and database paths</summary>{path_field('variant_annovar_dir','ANNOVAR installation')}{path_field('variant_annovar_db','ANNOVAR database folder',hint='Requires a matching reference build and an unpacked RefSeq TXT / Mrna FASTA pair. Optional ClinVar uses the same build.')}</details><p class="hint">If unavailable, calling results are retained and annotation is reported as unavailable. Installation help appears in resource details.</p></div>
</section></div>'''
