"""Existing-BAM variant setup, using the same local design as FASTQ setup."""

from .web_ui import PAGE as _SETUP_PAGE

_STYLE = _SETUP_PAGE.split("<style>", 1)[1].split("</style>", 1)[0]

PAGE = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>OncoTracer · Variants from aligned reads</title><style>''' + _STYLE + r'''
.small-choice{min-height:92px;padding:18px}.small-choice[aria-pressed=true]{padding:17px}.small-choice strong{font-size:19px}.path{font:12px/1.6 ui-monospace,monospace;overflow-wrap:anywhere}.callers{display:flex;gap:12px;flex-wrap:wrap;margin:12px 0 20px}.caller{border:1px solid var(--line);border-radius:8px;padding:12px 16px;display:flex;gap:9px;align-items:center;margin:0}.caller:has(input:checked){background:var(--wash);border-color:var(--accent)}.subsection{border-top:1px solid var(--line);margin-top:25px;padding-top:22px}.statusline{display:flex;align-items:center;gap:14px;flex-wrap:wrap}.statusline h2{margin-right:auto}#sample-table td:first-child{width:auto;min-width:140px}#sample-table td:last-child{min-width:220px}.reference-box{background:#f5f7f8;border-radius:7px;padding:12px 14px;margin:15px 0}.reference-box strong{display:block;font-size:12px;color:var(--muted);margin-bottom:5px}.runmetrics{display:flex;gap:24px;flex-wrap:wrap;margin:12px 0}.runmetrics strong{display:block}.runmetrics span{color:var(--muted);font-size:12px}.navigation{color:var(--accent);text-decoration:none;font-size:14px}.navigation:hover{text-decoration:underline}#config-path{font-size:14px}.logs:empty{display:none}
#progress-card[data-state=partial_failure]{border-color:#d9bc70;background:#fffdf6}#progress-card[data-state=partial_failure] #job-status{color:#78591b}#progress-card[data-state=partial_failure] #job-badge{color:#78591b;background:#f7eccb}.status-note{padding:12px 15px;border-radius:7px;background:#f7eccb;color:#634d22;font-size:14px}#progress-card[data-state=failed]{border-color:#dfada7}#progress-card[data-state=failed] #job-status{color:#8b2922}#progress-card[data-state=failed] .status-note{background:#fff0ee;color:#8b2922}#log-details>summary{font-size:14px;padding:8px 0}
</style></head><body>
<header><div class="brand">Onco<span>Tracer</span></div><a id="fastq-link" class="navigation" href="/">FASTQ analysis setup →</a></header>
<main><div class="intro"><div class="eyebrow">Small variants · Existing BAMs</div><h1>Assess variants from aligned reads</h1><p class="muted">Load an existing configuration, review the specimen and callers, and run the analysis in a new project folder. Follow progress and open its results here.</p></div>
<div id="error" role="alert" class="error" hidden></div>
<section class="card" id="input-card"><div class="sectionhead"><span class="step">1</span><h2>Load aligned samples</h2></div>
<label for="config-path">Existing variant configuration (YAML)</label><div class="row"><input id="config-path" autocomplete="off" spellcheck="false" placeholder="/path/to/variant_config.yml"><button data-browse="config-path" data-kind="file">Browse</button><button id="load-config" class="primary">Load samples</button></div>
<p class="hint">The configuration supplies the BAM manifest and reference FASTA. Review the samples below before preparing the new run.</p>
<div id="loaded-inputs" hidden><div class="statusline"><h3>Included samples</h3><span id="platform-badge" class="badge"></span><span id="sample-count" class="hint"></span></div><div class="samplewrap"><table id="sample-table"><thead><tr><th>Sample</th><th>Role</th><th>Aligned reads</th></tr></thead><tbody id="sample-rows"></tbody></table></div><div class="reference-box"><strong>Reference FASTA</strong><div id="reference-path" class="path"></div></div><div id="manifest-path" class="path muted"></div></div></section>
<div id="workflow" hidden>
<section class="card" id="settings-card"><div class="sectionhead"><span class="step">2</span><h2>Choose variant settings</h2></div>
<label>Specimen preservation</label><div class="grid"><button id="specimen-fresh" class="platform small-choice" aria-pressed="false"><strong>Fresh</strong><span>Fresh or frozen material</span></button><button id="specimen-ffpe" class="platform small-choice" aria-pressed="false"><strong>FFPE</strong><span>Formalin-fixed, paraffin-embedded material</span></button></div>
<h3>Variant callers</h3><p id="caller-note" class="hint"></p><div id="callers" class="callers"></div>
<div class="grid"><div><label for="threads">CPU threads</label><input id="threads" type="number" min="1" step="1" value="4"></div><div><label for="variant_targets_bed">Target regions BED (optional)</label><div class="row"><input id="variant_targets_bed" placeholder="Empty = whole genome"><button data-browse="variant_targets_bed" data-kind="asset">Browse</button></div></div></div>
<div class="field"><label for="variant_tool_prefix">Variant tool environment (optional)</label><div class="row"><input id="variant_tool_prefix" placeholder="Conda environment prefix; otherwise use detected tools"><button data-browse="variant_tool_prefix" data-kind="folder">Browse</button></div></div>
<div id="clair3-fields" class="subsection" hidden><h3>Clair3 model</h3><label for="variant_clair3_model">Chemistry-compatible Clair3 model folder</label><div class="row"><input id="variant_clair3_model"><button data-browse="variant_clair3_model" data-kind="folder">Browse</button></div></div>
<div id="clairsto-fields" class="subsection" hidden><h3>ClairS-TO model</h3><div class="grid"><div><label for="variant_clairsto_platform">Platform / model preset</label><input id="variant_clairsto_platform" placeholder="ont_r10_dorado_sup_5khz"></div><div><label for="variant_clairsto_sif">Existing ClairS-TO SIF (optional)</label><div class="row"><input id="variant_clairsto_sif"><button data-browse="variant_clairsto_sif" data-kind="asset">Browse</button></div></div></div></div>
<div id="ffperase-section" class="subsection" hidden><h3>FFPERASE artifact assessment</h3><label for="variant_ffperase">FFPE-specific filtering</label><select id="variant_ffperase"><option value="required">Run FFPERASE (required)</option><option value="off">Skip FFPERASE</option></select><p class="hint">Combines model-based artifact assessment with the caller's existing filters. If coverage is insufficient for the model, the result records that FFPERASE could not assess the variants.</p>
<div id="ffperase-resource-fields" class="grid"><div><label for="variant_ffperase_root">FFPERASE source folder</label><div class="row"><input id="variant_ffperase_root"><button data-browse="variant_ffperase_root" data-kind="folder">Browse</button></div></div><div><label for="variant_ffperase_models">FFPERASE models folder</label><div class="row"><input id="variant_ffperase_models"><button data-browse="variant_ffperase_models" data-kind="folder">Browse</button></div></div><div><label for="variant_ffperase_prefix">Native FFPERASE environment</label><div class="row"><input id="variant_ffperase_prefix"><button data-browse="variant_ffperase_prefix" data-kind="folder">Browse</button></div></div><div><label for="variant_ffperase_sif">FFPERASE SIF (alternative to native environment)</label><div class="row"><input id="variant_ffperase_sif"><button data-browse="variant_ffperase_sif" data-kind="asset">Browse</button></div></div></div></div>
<div class="subsection"><h3>Varlociraptor evidence assessment</h3><label for="variant_varlociraptor">Probabilistic filtering</label><select id="variant_varlociraptor"><option value="off">Skip Varlociraptor</option><option value="required">Run Varlociraptor and local FDR filtering</option></select>
<div id="varlociraptor-fields" hidden><div class="field"><label for="variant_varlociraptor_fdr">Local false discovery rate</label><input id="variant_varlociraptor_fdr" type="number" min="0.000001" max="0.999999" step="any" value="0.05"></div><p class="hint">The default model assesses variant presence. Original genotypes and caller filters remain in the resulting VCF.</p>
<details><summary>Custom scenario (optional)</summary><label for="variant_varlociraptor_scenario">Scenario YAML</label><div class="row"><input id="variant_varlociraptor_scenario"><button data-browse="variant_varlociraptor_scenario" data-kind="file">Browse</button></div><div class="grid"><div><label for="variant_varlociraptor_events">Events (comma-separated)</label><input id="variant_varlociraptor_events" value="PRESENT"></div><div><label for="variant_varlociraptor_sample">Observed sample name in scenario</label><input id="variant_varlociraptor_sample" value="sample"></div></div></details></div></div>
<div class="subsection"><h3>Variant annotation</h3><label for="variant_annovar">ANNOVAR</label><select id="variant_annovar"><option value="auto">Automatically use an existing local installation</option><option value="off">Skip ANNOVAR annotation</option></select><div id="annovar-fields" class="grid"><div><label for="variant_annovar_dir">ANNOVAR installation (optional)</label><div class="row"><input id="variant_annovar_dir"><button data-browse="variant_annovar_dir" data-kind="folder">Browse</button></div></div><div><label for="variant_annovar_db">Local ANNOVAR database (optional)</label><div class="row"><input id="variant_annovar_db"><button data-browse="variant_annovar_db" data-kind="folder">Browse</button></div></div></div><p class="hint">Auto uses installed software and local annotation databases. Annotation availability appears separately in the report.</p></div></section>
<section class="card" id="project-card"><div class="sectionhead"><span class="step">3</span><h2>Save and review the run</h2></div><label for="project">New project folder</label><div class="row"><input id="project" autocomplete="off" spellcheck="false"><button id="browse-project-parent">Choose parent</button></div><p class="hint">Choose a new folder for this run's configuration, logs, and results.</p><div class="actions"><button id="prepare" class="primary">Save and check settings</button><span id="dirty-note" class="hint">Review and save settings before starting.</span></div></section>
</div>
<section class="card" id="review-card" hidden><div class="statusline"><h2>Ready for review</h2><span id="check-badge" class="badge"></span></div><p id="saved-path" class="path"></p><div id="check-messages"></div><details><summary>Saved configuration</summary><pre id="config-preview"></pre></details><div class="actions"><button id="run" class="primary" disabled>Run variant analysis</button></div></section>
<section class="card" id="progress-card" hidden><div class="statusline"><h2 id="job-status">Analysis running</h2><span id="job-badge" class="badge"></span></div><p id="job-note" class="status-note" role="status" hidden></p><p id="run-stage" class="muted" aria-live="polite"></p><div class="runmetrics"><div><strong id="run-elapsed">—</strong><span>Elapsed</span></div><div><strong id="run-eta">—</strong><span>Estimated remaining</span></div></div><details id="log-details" open><summary>Raw execution log</summary><pre id="logs" class="logs" tabindex="0" aria-label="Analysis log"></pre><p id="log-path" class="path muted"></p></details><div class="actions"><button id="stop">Stop analysis</button><a id="open-results" class="result-link" target="_blank" rel="noopener" hidden>Open results</a><button id="edit-next" hidden>Prepare another run</button></div></section>
<footer>OncoTracer · Local analysis workspace</footer></main>
<dialog id="browser"><div class="sectionhead"><h2 id="browser-title">Select a folder</h2><button id="close-browser" style="margin-left:auto">Close</button></div><nav id="browser-shortcuts" class="browser-shortcuts" aria-label="Computer locations"></nav><div id="browser-error" class="error" role="alert" hidden></div><div class="row"><input id="browser-location" aria-label="Folder path"><button id="browser-go">Go</button><button id="browser-up">Up</button></div><p id="browser-path" class="folderpath"></p><div id="folders" class="folders"></div><p id="browser-note" class="hint"></p><div class="actions"><button id="use-folder" class="primary">Use this folder</button></div></dialog>
<script>
'use strict';
const $=id=>document.getElementById(id),show=(id,yes)=>$(id).hidden=!yes,token=location.hash.slice(1);
const resourceFields=['variant_targets_bed','variant_tool_prefix','variant_clair3_model','variant_clairsto_platform','variant_clairsto_sif','variant_annovar_dir','variant_annovar_db','variant_ffperase_root','variant_ffperase_models','variant_ffperase_prefix','variant_ffperase_sif','variant_varlociraptor_scenario'];
const scalarFields=['variant_annovar','variant_ffperase','variant_varlociraptor','variant_varlociraptor_fdr','variant_varlociraptor_events','variant_varlociraptor_sample'];
const callerChoices={illumina:[['mutect2','Mutect2'],['freebayes','FreeBayes'],['bcftools','BCFtools']],ont:[['clair3','Clair3'],['clairs_to','ClairS-TO']]};
let loaded=null,prepared=null,mode=null,specimen=null,activeJob=null,busyNow=false,runActive=false,pollTimer=null,system=null,browserTarget=null,browserKind='folder',currentFolder='',parentFolder='',browseSequence=0;
function node(tag,text,cls){const element=document.createElement(tag);if(text!==undefined)element.textContent=text;if(cls)element.className=cls;return element;}
function fail(error,id='error'){$(id).textContent=error.message||String(error);show(id,true);}
async function api(path,data){let response;try{response=await fetch(path,{method:data?'POST':'GET',headers:{'X-OncoTracer-Token':token,...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});}catch(error){throw Error('Cannot reach OncoTracer. Keep its terminal open and use the complete session URL printed there.');}const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed.');return result;}
function lockSettings(){for(const field of document.querySelectorAll('#input-card input,#input-card button,#workflow input,#workflow select,#workflow button'))field.disabled=runActive||busyNow;$('run').disabled=runActive||busyNow||!prepared?.valid;}
async function busy(action){if(busyNow||runActive)return;busyNow=true;show('error',false);lockSettings();try{await action();}catch(error){fail(error);}finally{busyNow=false;lockSettings();}}
function invalidate(){if(runActive)return;prepared=null;show('review-card',false);$('run').disabled=true;$('dirty-note').textContent='Settings changed. Save and check before starting.';}
function callers(){return [...document.querySelectorAll('#callers input:checked')].map(input=>input.value);}
function updateSettings(){resetVariantResourceResults();show('ffperase-section',mode==='illumina'&&specimen==='ffpe');show('ffperase-resource-fields',$('variant_ffperase').value==='required');show('varlociraptor-fields',$('variant_varlociraptor').value==='required');show('annovar-fields',$('variant_annovar').value==='auto');show('clair3-fields',mode==='ont'&&callers().includes('clair3'));show('clairsto-fields',mode==='ont'&&callers().includes('clairs_to'));for(const value of ['fresh','ffpe'])$('specimen-'+value).setAttribute('aria-pressed',String(specimen===value));}
function selectSpecimen(value){if(runActive||busyNow)return;specimen=value;updateSettings();invalidate();}
$('specimen-fresh').onclick=()=>selectSpecimen('fresh');$('specimen-ffpe').onclick=()=>selectSpecimen('ffpe');
function renderLoaded(result){loaded=result;mode=result.mode||result.config.mode;const config=result.config;specimen=config.variant_specimen_type||'fresh';for(const key of resourceFields)$(key).value=config[key]??'';const defaults={variant_annovar:'auto',variant_ffperase:'required',variant_varlociraptor:'off',variant_varlociraptor_fdr:'0.05',variant_varlociraptor_events:'PRESENT',variant_varlociraptor_sample:'sample'};for(const key of scalarFields)$(key).value=config[key]??defaults[key];if(mode!=='illumina'||specimen!=='ffpe')$('variant_ffperase').value='required';$('threads').value=config.threads||system.suggested_threads||4;$('project').value=result.suggested_project;
  const selected=new Set((Array.isArray(config.variant_callers)?config.variant_callers:String(config.variant_callers||(mode==='illumina'?'mutect2':'clair3')).split(',')).map(value=>value.trim()));$('callers').replaceChildren();for(const [value,label]of callerChoices[mode]||[]){const wrapper=node('label',undefined,'caller'),input=document.createElement('input');input.type='checkbox';input.value=value;input.id='caller-'+value;input.checked=selected.has(value);input.onchange=()=>{updateSettings();invalidate();};wrapper.append(input,document.createTextNode(label));$('callers').append(wrapper);}
  $('caller-note').textContent=mode==='illumina'?'Choose one or more callers for Illumina reads. Each retains its own calls and filters.':'Choose one or both callers with the model matching the ONT chemistry and basecaller.';$('platform-badge').textContent=mode==='illumina'?'Illumina':'Oxford Nanopore';$('sample-count').textContent=result.samples.length+' sample'+(result.samples.length===1?'':'s');$('reference-path').textContent=config.variant_reference||'';$('manifest-path').textContent='BAM manifest: '+(config.variant_bam_manifest||'');$('sample-rows').replaceChildren();for(const sample of result.samples){const row=node('tr');row.append(node('td',sample.sample),node('td',sample.status==='normal'?'Normal':'Tumor'),node('td',sample.bam,'path'));$('sample-rows').append(row);}show('loaded-inputs',true);show('workflow',true);updateSettings();invalidate();$('dirty-note').textContent='Loaded. Review and save settings before starting.';
}
async function loadConfig(){if(!$('config-path').value.trim())throw Error('Choose an existing variant configuration.');const result=await api('/api/variant-load',{config_path:$('config-path').value.trim()});renderLoaded(result);}
$('load-config').onclick=()=>busy(loadConfig);$('config-path').onkeydown=event=>{if(event.key==='Enter')$('load-config').click();};
$('config-path').oninput=()=>{loaded=null;invalidate();show('loaded-inputs',false);show('workflow',false);};
for(const field of document.querySelectorAll('#settings-card input,#settings-card select,#project'))field.addEventListener('input',()=>{updateSettings();invalidate();});
function payload(){if(!loaded)throw Error('Load a variant configuration first.');if(!callers().length)throw Error('Select at least one variant caller.');const threads=Number($('threads').value);if(!Number.isInteger(threads)||threads<1)throw Error('CPU threads must be a positive integer.');if(!specimen)throw Error('Choose Fresh or FFPE.');const data={load_id:loaded.load_id,project:$('project').value.trim(),threads,variant_specimen_type:specimen,variant_callers:callers().join(',')};if(!data.project)throw Error('Choose a new project folder.');for(const key of [...resourceFields,...scalarFields])data[key]=$(key).value.trim();if(mode!=='illumina'||specimen!=='ffpe')data.variant_ffperase='off';if(data.variant_ffperase==='off')for(const key of ['variant_ffperase_root','variant_ffperase_models','variant_ffperase_prefix','variant_ffperase_sif'])data[key]='';if(data.variant_annovar==='off'){data.variant_annovar_dir='';data.variant_annovar_db='';}if(data.variant_varlociraptor==='off')for(const key of ['variant_varlociraptor_fdr','variant_varlociraptor_scenario','variant_varlociraptor_events','variant_varlociraptor_sample'])data[key]='';if(!callers().includes('clair3'))data.variant_clair3_model='';if(!callers().includes('clairs_to')){data.variant_clairsto_platform='';data.variant_clairsto_sif='';}if(data.variant_varlociraptor==='required'){const fdr=Number(data.variant_varlociraptor_fdr);if(!Number.isFinite(fdr)||fdr<=0||fdr>=1)throw Error('Local false discovery rate must be greater than 0 and less than 1.');}return data;}
$('prepare').onclick=()=>busy(async()=>{const result=await api('/api/variant-prepare',payload());prepared=result;$('saved-path').textContent='Saved: '+result.config_path;$('config-preview').textContent=result.config;$('check-badge').textContent=result.valid?'Settings checked':'Needs attention';$('check-messages').replaceChildren();for(const error of result.check?.errors||[])$('check-messages').append(node('p',typeof error==='string'?error:JSON.stringify(error),'error'));for(const warning of result.check?.warnings||[])$('check-messages').append(node('p',typeof warning==='string'?warning:JSON.stringify(warning),'notice'));$('dirty-note').textContent=result.valid?'Settings saved and checked.':'Review the messages below.';show('review-card',true);$('run').hidden=false;$('review-card').scrollIntoView({behavior:'smooth',block:'start'});});
function duration(seconds){if(seconds===null||seconds===undefined)return 'Not yet known';const n=Math.max(0,Math.round(seconds)),h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=n%60;return(h?h+'h ':'')+(h||m?m+'m ':'')+s+'s';}
function renderJobStatus(job){
  const partial=job.status==='partial_failure',active=['running','stopping'].includes(job.status);
  const labels={running:'Variant analysis running',stopping:'Stopping analysis',stopped:'Variant analysis stopped',complete:'Variant analysis completed',partial_failure:'Partial failure',removed:'Project removed'};
  $('progress-card').dataset.state=job.status;
  $('job-status').textContent=labels[job.status]||'Variant analysis failed';
  $('job-badge').textContent=active?job.status:partial?'Completed results retained':job.status==='complete'?'Complete':'Exit '+(job.exit_code??'—');
  $('job-note').textContent=partial?'Some required assessments could not be completed. Completed results are retained. Open the results to review the available outputs and unfinished assessments.':job.status==='failed'?'The analysis could not finish. Review the raw execution log for error details.':'';
  show('job-note',partial||job.status==='failed');
  const state=String(job.project_id)+':'+job.status;
  if($('log-details').dataset.jobState!==state){$('log-details').open=!partial;$('log-details').dataset.jobState=state;}
}
async function poll(){clearTimeout(pollTimer);try{const job=await api('/api/status');activeJob=job;if(job.status==='idle')return;runActive=['running','stopping'].includes(job.status);show('progress-card',true);$('run').hidden=true;renderJobStatus(job);const progress=job.progress||{};$('run-stage').textContent=job.stop_error||progress.stage||'';$('run-elapsed').textContent=duration(progress.elapsed_seconds);$('run-eta').textContent=runActive?duration(progress.overall_eta_seconds??progress.eta_seconds):'Finished';const log=$('logs'),atEnd=log.scrollHeight-log.scrollTop-log.clientHeight<50;log.textContent=(job.log_truncated?'[Latest log output; full log saved below.]\n':'')+(job.log||'');if(atEnd)log.scrollTop=log.scrollHeight;$('log-path').textContent=job.log_path?'Full log: '+job.log_path:'';show('stop',runActive);$('stop').disabled=job.status==='stopping'&&!job.stop_error;show('edit-next',!runActive);if(job.results_url){$('open-results').href=job.results_url;show('open-results',true);}lockSettings();if(runActive)pollTimer=setTimeout(poll,1200);}catch(error){fail(error);if(runActive)pollTimer=setTimeout(poll,2500);}}
$('run').onclick=()=>busy(async()=>{if(!prepared?.valid)throw Error('Save and check the settings before running.');await api('/api/run',{project_id:prepared.id});runActive=true;show('open-results',false);$('open-results').removeAttribute('href');await poll();$('progress-card').scrollIntoView({behavior:'smooth',block:'start'});});
$('stop').onclick=async()=>{if(!activeJob||!runActive)return;$('stop').disabled=true;try{await api('/api/stop',{project_id:activeJob.project_id});await poll();}catch(error){fail(error);$('stop').disabled=false;}};
$('edit-next').onclick=async()=>{if(runActive)return;if(!loaded){if($('config-path').value.trim())await busy(loadConfig);else{$('input-card').scrollIntoView({behavior:'smooth'});$('config-path').focus();}return;}prepared=null;show('review-card',false);$('project').value=$('project').value.replace(/_rerun_\d+$/,'')+'_rerun_'+Date.now();$('run').hidden=false;$('dirty-note').textContent='Choose settings and save a new project.';lockSettings();$('project-card').scrollIntoView({behavior:'smooth'});};
function choosePath(path){if(browserTarget==='project-parent'){const leaf=$('project').value.replace(/\/$/,'').split('/').pop()||'variants_'+Date.now();$('project').value=path.replace(/\/$/,'')+'/'+leaf;invalidate();}else{$(browserTarget).value=path;$(browserTarget).dispatchEvent(new Event('input',{bubbles:true}));}$('browser').close();}
async function browse(path){const sequence=++browseSequence;show('browser-error',false);$('use-folder').disabled=true;try{const result=await api('/api/browse?path='+encodeURIComponent(path||system.start_dir)+'&kind='+encodeURIComponent(browserKind));if(sequence!==browseSequence)return;currentFolder=result.path;parentFolder=result.parent;$('browser-location').value=result.path;$('browser-path').textContent=result.path;$('folders').replaceChildren();for(const directory of result.directories){const button=node('button',directory.name,'folder');button.onclick=()=>browse(directory.path);$('folders').append(button);}if(browserKind!=='folder')for(const file of result.files||[]){if(browserKind==='file'&&!/\.ya?ml$/i.test(file.name))continue;const button=node('button','File · '+file.name,'folder');button.onclick=()=>choosePath(file.path);$('folders').append(button);}if(!$('folders').children.length)$('folders').append(node('p','No folders or matching files here.','hint'));$('browser-note').textContent=result.truncated?'Listing limited to 1,000 entries per type.':'Open a folder to browse its contents.';$('use-folder').disabled=browserKind!=='folder';}catch(error){if(sequence===browseSequence)fail(error,'browser-error');}}
function openBrowser(target,kind='folder'){if(runActive||busyNow)return;browserTarget=target;browserKind=kind;$('browser-title').textContent=kind==='folder'?'Select a folder':'Select a file';show('use-folder',kind==='folder');$('browser').showModal();let path=target==='project-parent'?$('project').value.replace(/\/[^/]*\/?$/,''):$(target).value;return browse(path||system.start_dir);}
for(const button of document.querySelectorAll('[data-browse]'))button.onclick=()=>openBrowser(button.dataset.browse,button.dataset.kind||'folder');$('browse-project-parent').onclick=()=>openBrowser('project-parent');$('close-browser').onclick=()=>$('browser').close();$('browser').addEventListener('close',()=>{browseSequence++;});$('browser-go').onclick=()=>browse($('browser-location').value);$('browser-up').onclick=()=>browse(parentFolder);$('browser-location').oninput=()=>{$('use-folder').disabled=true;$('browser-note').textContent='Press Enter or Go to open this path.';};$('browser-location').onkeydown=event=>{if(event.key==='Enter')browse(event.target.value);};$('use-folder').onclick=()=>choosePath(currentFolder);
$('fastq-link').href='/#'+token;
(async()=>{try{if(!token)throw Error('Open the complete OncoTracer URL, including the session code after #.');system=await api('/api/system');for(const place of system.locations||[]){const button=node('button',place.name);button.title=place.path;button.onclick=()=>browse(place.path);$('browser-shortcuts').append(button);}const defaults=system.defaults||{};$('threads').value=system.suggested_threads||4;await poll();if(defaults.variant_config){$('config-path').value=defaults.variant_config;if(!runActive)await busy(loadConfig);}}catch(error){fail(error);}})();
</script></body></html>'''

from .variant_resource_ui import add_resource_ui

PAGE = add_resource_ui(PAGE, existing_bam=True)
